name: Versions
on:
  pull_request

jobs:
  dco-helper:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: console.log(context);
      - name: log
        uses: actions/github-script@v5
        with:
          script: console.log('bop');
      - name: Checks
        uses: actions/github-script@v5
        with:
          script: |
            const owner = "jhaals";
            const repo = "release-test";
            const ref = process.env.GITHUB_HEAD_REF;
            console.log(process.env);
            const pr = context.payload.number;

            const r = await github.rest.checks.listForRef({
              owner,
              repo,
              ref,
              check_name: "DCO",
              status: "completed",
            });
            
            if (r.data.check_runs[0].conclusion !== "action_required") {
              console.log("NO actions required, skipping");
              return;
            }

            const comments = await github.rest.issues.listComments({
                owner,
                repo,
                issue_number: pr,
              });
            console.log(JSON.stringify(comments.data, null, 2));
            if (comments.data.find((c) => c.user.login === "bop")) {
              console.log("already commented, skipping");
              return;
            }
            await github.rest.issues.createComment({
              repo,
              owner,
              issue_number: pr,
              body: "DCO signing needed",
            });
