name: Sync Issue Labels
on:
  issues:
    types: [opened]
jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.issue.title);
            
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            });
