name: DCO helper
on: workflow_dispatch

jobs:
  dco-helper:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      - name: Verify open pull requests
        uses: actions/github-script@v5
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          script: |
            const owner = "jhaals";
              const repo = "release-test";
              const pulls = await github.paginate(github.rest.pulls.list, {
                state: "open",
                owner,
                repo,
              });
              console.log(pulls);
              await github.rest.issues.createComment({
                repo,
                owner,
                issue_number: 15,
                body: 'test',
              });