name: Sync Approve renovate lock file changes
on:
  pull_request_target:
    paths:
      - '.github/workflows/sync_renovate-changesets.yml'
      - '**/yarn.lock'

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' && github.repository == 'jhaals/release-test'
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 2
      #     ref: ${{ github.head_ref }}
#          token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            if (context.payload.changed_files !== 3) {
              console.log('Skipping auto approval since more files were changed than expected');
              return
            }
            github.pulls.createReview({
              pull_number: context.payload.number,
              event: 'APPROVE'
            })
            }