name: Versions
on:
  pull_request

jobs:
  dco-helper:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: console.log(context);
      - name: log
        uses: actions/github-script@v5
        with:
          script: console.log('bop');
      - name: Checks
        uses: actions/github-script@v5
        with:
          script: |
            const owner = "jhaals";
            const repo = "release-test";
            const ref = process.env.GITHUB_REF_NAME;
            console.log(ref);
            console.log(process.env.GITHUB_BASE_REF);
            console.log(process.env);
            const pr = context.payload.number;

            const r = await github.rest.checks.listForRef({
              owner,
              repo,
              ref,
              check_name: "DCO",
              status: "completed",
            });
            console.log(r);
