name: Versions
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.1'
jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout versions
        uses: actions/checkout@v2
        with:
          repository: backstage/versions
          path: versions
      - name: Configure Git
        run: |
          git config --global user.email noreply@backstage.io
          git config --global user.name 'Github versions workflow'
      - name: Configure Git
        run: |
          cd versions
          echo winning > ${{ github.event.inputs.version }}
          git add ${{ github.event.inputs.version }}
          git commit -m "${{ github.event.inputs.version }}"
          git push
