name: Versions
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.1'
jobs:
  create-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout versions
        uses: actions/checkout@v2
        with:
          repository: backstage/versions
          path: versions
      - name: Configure Git
        run: |
          git config --global user.email noreply@backstage.io
          git config --global user.name 'Github versions workflow'
      - name: Create release
        run: |
          cd versions
          echo winning > ${{ github.event.inputs.version }}
          if [[ "${{ github.event.inputs.version }}" == *"next"* ]]; then
            echo Updating next tag
            ln -s ../releases/${{ github.event.inputs.version }} tags/next
            else
            echo Updating main tag
            ln -s ../releases/${{ github.event.inputs.version }} tags/main
          fi
          git add .
          git commit -am "${{ github.event.inputs.version }}"
          git push
