name: Sync Approve renovate lock file changes
on:
  workflow_dispatch:

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo hello
          echo world
          false
          echo winning should not show
