name: Versions
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.1'
jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout versions
        uses: actions/checkout@v2
        with:
          repository: backstage/versions
          path: versions
